In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

In [2]:
dataloc = "data"
carhacking = "Car_Hacking_Challenge_Dataset_rev20Mar2021"
prelim = "0_Preliminary"
training = "0_Training"
filename_0 = "Pre_train_D_0.csv"

In [64]:
import os

prelim_train_dir = os.path.join("..", dataloc, "raw", carhacking, prelim, training)
csv0 = os.path.join(prelim_train_dir, filename_0)

In [65]:
df = pd.read_csv(csv0)
df.head()

Timestamp Arbitration_ID  DLC                     Data   Class
0  1.597708e+09            260    8  06 25 05 30 FF CF 71 55  Normal
1  1.597708e+09            329    8  4A C5 7E 8C 31 2D 01 10  Normal
2  1.597708e+09            38D    8  00 00 49 00 90 7F FE 01  Normal
3  1.597708e+09            420    8  50 1E 00 C8 FC 4F 6A 00  Normal
4  1.597708e+09            421    8  FE 07 00 FF E3 7F 00 52  Normal

In [66]:
df[["d1", "d2", "d3", "d4", "d5", "d6", "d7", "d8"]] = df.Data.str.split(" ", expand=True)
df.head()

Timestamp Arbitration_ID  DLC                     Data   Class  d1  d2  \
0  1.597708e+09            260    8  06 25 05 30 FF CF 71 55  Normal  06  25   
1  1.597708e+09            329    8  4A C5 7E 8C 31 2D 01 10  Normal  4A  C5   
2  1.597708e+09            38D    8  00 00 49 00 90 7F FE 01  Normal  00  00   
3  1.597708e+09            420    8  50 1E 00 C8 FC 4F 6A 00  Normal  50  1E   
4  1.597708e+09            421    8  FE 07 00 FF E3 7F 00 52  Normal  FE  07   

   d3  d4  d5  d6  d7  d8  
0  05  30  FF  CF  71  55  
1  7E  8C  31  2D  01  10  
2  49  00  90  7F  FE  01  
3  00  C8  FC  4F  6A  00  
4  00  FF  E3  7F  00  52

In [67]:
df["d3"].isna().sum()

298

In [69]:
df["d1_int"] = df.apply(lambda x: 999 if x["d1"] is None else int(x["d1"], 16), axis=1)
df["d2_int"] = df.apply(lambda x: 999 if x["d2"] is None else int(x["d2"], 16), axis=1)
df["d3_int"] = df.apply(lambda x: 999 if x["d3"] is None else int(x["d3"], 16), axis=1)
df["d4_int"] = df.apply(lambda x: 999 if x["d4"] is None else int(x["d4"], 16), axis=1)

df["d5_int"] = df.apply(lambda x: 999 if x["d5"] is None else int(x["d5"], 16), axis=1)
df["d6_int"] = df.apply(lambda x: 999 if x["d6"] is None else int(x["d6"], 16), axis=1)
df["d7_int"] = df.apply(lambda x: 999 if x["d7"] is None else int(x["d7"], 16), axis=1)
df["d8_int"] = df.apply(lambda x: 999 if x["d8"] is None else int(x["d8"], 16), axis=1)

In [70]:
df

Timestamp Arbitration_ID  DLC                     Data   Class  d1  \
0       1.597708e+09            260    8  06 25 05 30 FF CF 71 55  Normal  06   
1       1.597708e+09            329    8  4A C5 7E 8C 31 2D 01 10  Normal  4A   
2       1.597708e+09            38D    8  00 00 49 00 90 7F FE 01  Normal  00   
3       1.597708e+09            420    8  50 1E 00 C8 FC 4F 6A 00  Normal  50   
4       1.597708e+09            421    8  FE 07 00 FF E3 7F 00 52  Normal  FE   
...              ...            ...  ...                      ...     ...  ..   
179341  1.597708e+09            391    8  00 00 00 00 00 00 08 EB  Normal  00   
179342  1.597708e+09            260    8  06 39 1A 30 FF D1 A1 63  Normal  06   
179343  1.597708e+09            421    8  FE 07 00 FF E3 7F 00 9E  Normal  FE   
179344  1.597708e+09            130    8  94 8E F0 81 00 00 0B AC  Normal  94   
179345  1.597708e+09            140    8  30 80 00 6F 20 00 0B 35  Normal  30   

        d2  d3  d4  d5  ...  d7  d8 d1_int  d2_int  d3_int  d4_int  d5_int  \
0       25  05  30  FF  ...  71  55      6      37       5      48     255   
1       C5  7E  8C  31  ...  01  10     74     197     126     140      49   
2       00  49  00  90  ...  FE  01      0       0      73       0     144   
3       1E  00  C8  FC  ...  6A  00     80      30       0     200     252   
4       07  00  FF  E3  ...  00  52    254       7       0     255     227   
...     ..  ..  ..  ..  ...  ..  ..    ...     ...     ...     ...     ...   
179341  00  00  00  00  ...  08  EB      0       0       0       0       0   
179342  39  1A  30  FF  ...  A1  63      6      57      26      48     255   
179343  07  00  FF  E3  ...  00  9E    254       7       0     255     227   
179344  8E  F0  81  00  ...  0B  AC    148     142     240     129       0   
179345  80  00  6F  20  ...  0B  35     48     128       0     111      32   

        d6_int  d7_int  d8_int  
0          207     113      85  
1           45       1      16  
2          127     254       1  
3           79     106       0  
4          127       0      82  
...        ...     ...     ...  
179341       0       8     235  
179342     209     161      99  
179343     127       0     158  
179344       0      11     172  
179345       0      11      53  

[179346 rows x 21 columns]

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 179346 entries, 0 to 179345
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Timestamp       179346 non-null  float64
 1   Arbitration_ID  179346 non-null  object 
 2   DLC             179346 non-null  int64  
 3   Data            179346 non-null  object 
 4   Class           179346 non-null  object 
 5   d1              179346 non-null  object 
 6   d2              179346 non-null  object 
 7   d3              179048 non-null  object 
 8   d4              179048 non-null  object 
 9   d5              164043 non-null  object 
 10  d6              160310 non-null  object 
 11  d7              152472 non-null  object 
 12  d8              145007 non-null  object 
 13  d1_int          179346 non-null  int64  
 14  d2_int          179346 non-null  int64  
 15  d3_int          179346 non-null  int64  
 16  d4_int          179346 non-null  int64  
 17  d5_int    

In [74]:
X = df[["d1_int", "d2_int", "d3_int", "d4_int", "d5_int", "d6_int", "d7_int", "d8_int"]].to_numpy()
X

array([[  6,  37,   5, ..., 207, 113,  85],
       [ 74, 197, 126, ...,  45,   1,  16],
       [  0,   0,  73, ..., 127, 254,   1],
       ...,
       [254,   7,   0, ..., 127,   0, 158],
       [148, 142, 240, ...,   0,  11, 172],
       [ 48, 128,   0, ...,   0,  11,  53]], dtype=int64)

In [76]:
X.shape

(179346, 8)

In [83]:
import math

def build_nonoverlapping_sequence(X, seq_num=4):
    seq_len = X.shape[1] * seq_num
    n = math.floor(X.shape[0] / seq_len)
    r = X.shape[0] % seq_len
    if r != 0:
        # Cut off not divisible part
        seqs = X[:-r].reshape(-1,32)
    else:
        seqs = X.reshape(-1,32)

    return seqs

In [85]:
Xnew = build_nonoverlapping_sequence(X, 32)
Xnew.shape

(44832, 32)

In [86]:
Xnew[0]

array([  6,  37,   5,  48, 255, 207, 113,  85,  74, 197, 126, 140,  49,
        45,   1,  16,   0,   0,  73,   0, 144, 127, 254,   1,  80,  30,
         0, 200, 252,  79, 106,   0], dtype=int64)

In [87]:
from abc import ABC, abstractmethod

class UnsupervisedEmbedding(ABC):
    def __init__(self, embedding_root: str = None, embedding_for: str = None,
                 embedding_dim: int = 100, embedding_version: float = 1.0):
        self.embedding_root = embedding_root
        self.embedding_for = embedding_for
        self.embedding_dim = embedding_dim
        self.embedding_version = embedding_version

    @abstractmethod
    def fit(self, X):
        pass

In [88]:
import fasttext

In [97]:
def generate_model_file_path(embedding_root: str = None, embedding_for: str = None,
                             embedding_model='skipgram', embedding_wordNgrams: int = 1,
                             embedding_dim: int = 100, train_seq_len: int = 10, embedding_version: float = 1.0,
                             embedding_type='fasttext'):
    filename = f"{embedding_for}_{embedding_type}_{embedding_model}_" \
               f"{embedding_wordNgrams}wordNgram_{embedding_dim}dim_{train_seq_len}trainseq_v{embedding_version}.bin"
    print(os.path.join(embedding_root, filename))
    return os.path.join(embedding_root, filename)

In [101]:
class FastTextEmbedding(UnsupervisedEmbedding):
    def __init__(self, embedding_root: str = None, embedding_for: str = None,
                 embedding_model='skipgram', embedding_wordNgrams: int = 1,
                 embedding_dim: int = 100, embedding_version: float = 1.0,
                 epochs: int = 10, minCount: int = 1, maxn: int = 0):
        super().__init__(embedding_root, embedding_for, embedding_dim, embedding_version)
        self.embedding_model = embedding_model

        # Can use wordN grams by setting 2
        # https://fasttext.cc/docs/en/supervised-tutorial.html
        self.embedding_wordNgrams = embedding_wordNgrams

        self.epochs = epochs
        self.minCount = minCount
        self.maxn = maxn

        self.embedding_config = {
            'embedding_root': self.embedding_root,
            'embedding_for': self.embedding_for, 'embedding_model': self.embedding_model,
            "embedding_wordNgrams": self.embedding_wordNgrams, 'embedding_dim': self.embedding_dim,
            'embedding_version': self.embedding_version, 'embedding_type': 'fasttext'
        }

    def fit(self, X):
        seq_len = X.shape[1]
        # if X is not None:
        #     seq_len = len(_tokenize_by_spaces(X[0])) 
        # print(f"Calc BBBBBBBBBB {seq_len} , X.shape[1] = {X.shape[1]}")


        data_temp_file_path = FastTextEmbedding.generate_temp_seq_storage_file_path(self.embedding_for)
        np.savetxt(data_temp_file_path, X.astype(int), fmt='%i')

        # Create embeddings for event id https://fasttext.cc/docs/en/python-module.html
        fasttext_model = fasttext.train_unsupervised(data_temp_file_path,
                                                     model=self.embedding_model,
                                                     dim=self.embedding_dim,
                                                     wordNgrams=self.embedding_wordNgrams,
                                                     epoch=self.epochs, minCount=self.minCount, maxn=self.maxn)
        cfg_copy = self.embedding_config.copy()
        cfg_copy["train_seq_len"] = seq_len
        model_file_path = generate_model_file_path(**cfg_copy)
        fasttext_model.save_model(model_file_path)

        os.remove(data_temp_file_path)

        # print(fasttext_model.get_words())
        # word_embeddings = model.get_output_matrix()
        # print(word_embeddings)

        return fasttext_model
    
    @staticmethod
    def generate_temp_seq_storage_file_path(embedding_for=None):
        return embedding_for + '_eventid_token_seq.txt'

In [107]:
fastText_embedding_cfg = {
    'embedding_root': "c:/carhacking/features",
    'embedding_for': "Car_Hacking_Challenge_Dataset_rev20Mar2021", 'embedding_model': "skipgram",
    "embedding_wordNgrams": 3, 'embedding_dim': 100,
    'embedding_version': "1.0"
}

fasttext_embedding = FastTextEmbedding(**fastText_embedding_cfg)
fasttext_model = fasttext_embedding.fit(Xnew) # fits and saves model

c:/carhacking/features\Car_Hacking_Challenge_Dataset_rev20Mar2021_fasttext_skipgram_3wordNgram_100dim_32trainseq_v1.0.bin


Fit fastText model

In [108]:
def fast_text_from_model_file(embedding_root: str = None, embedding_for: str = None,
                              embedding_model='skipgram', embedding_wordNgrams: int = 1,
                              embedding_dim: int = 100, train_seq_len: int = 10, embedding_version: float = 1.0):
    model_file_path = generate_model_file_path(embedding_root, embedding_for, embedding_model,
                                               embedding_wordNgrams, embedding_dim, train_seq_len,
                                               embedding_version, 'fasttext')
    model = fasttext.load_model(model_file_path)
    return model

Load embeddings

In [110]:
fastText_embedding_cfg = {
    'embedding_root': "c:/carhacking/features",
    'embedding_for': "Car_Hacking_Challenge_Dataset_rev20Mar2021", 'embedding_model': "skipgram",
    "embedding_wordNgrams": 3, 'embedding_dim': 100,
    'embedding_version': "1.0", "train_seq_len": 32
}

fasttext_model = fast_text_from_model_file(**fastText_embedding_cfg)
word_embeddings = np.array([fasttext_model.get_word_vector(str(word_token))
                            for word_token in np.arange(0,255)])

#TODO: Extract normalized embeddings and do DBSCAN clustering

c:/carhacking/features\Car_Hacking_Challenge_Dataset_rev20Mar2021_fasttext_skipgram_3wordNgram_100dim_32trainseq_v1.0.bin


In [111]:
word_embeddings

array([[ 0.01057254,  0.03097373,  0.04247935, ...,  0.0288514 ,
        -0.05428167, -0.06537412],
       [ 0.0090155 , -0.11649842,  0.02046471, ...,  0.00325844,
        -0.01161586, -0.1534308 ],
       [-0.0520121 ,  0.06144251,  0.17540129, ..., -0.09720963,
        -0.1723913 , -0.09780928],
       ...,
       [-0.4767333 , -0.00618175, -0.07802476, ...,  0.07237452,
         0.3546015 , -0.10663392],
       [ 0.3666228 ,  0.21565413, -0.1001232 , ...,  0.22993521,
         0.03435629, -0.07837205],
       [-0.43565574,  0.18863069,  0.30761448, ...,  0.1854385 ,
         0.2948535 ,  0.13150002]], dtype=float32)

Save file in word2vec format. This is compact and we dont need fancy fasttext sub word token embeddings that bloats its propreitory feature storage in bin file  

In [112]:
def generate_word2vec_model_file_path(embedding_root: str = None, embedding_for: str = None,
                             embedding_model='skipgram', embedding_wordNgrams: int = 1,
                             embedding_dim: int = 100, train_seq_len: int = 10, embedding_version: float = 1.0,
                             embedding_type='fasttext'):
    filename = f"{embedding_for}_{embedding_type}_{embedding_model}_" \
               f"{embedding_wordNgrams}wordNgram_{embedding_dim}dim_{train_seq_len}trainseq_v{embedding_version}.word2vec"
    return os.path.join(embedding_root, filename)

In [113]:
from gensim.models import Word2Vec, KeyedVectors

fastText_embedding_cfg = {
    'embedding_root': "c:/carhacking/features",
    'embedding_for': "Car_Hacking_Challenge_Dataset_rev20Mar2021", 'embedding_model': "skipgram",
    "embedding_wordNgrams": 3, 'embedding_dim': 100,
    'embedding_version': "1.0", "train_seq_len": 32
}

model_file_path = generate_word2vec_model_file_path(**fastText_embedding_cfg)

#wv = KeyedVectors.load_word2vec_format(model_file_path)
#wv_eventids = wv.index_to_key
#TODO